# Generated by Django 3.0.5 on 2021-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'T-Shirt'), ('SW', 'SportWear'), ('OW', 'OutWear')], max_length=2),
        ),
    ]
